# Generated by Django 6.0.2 on 2026-02-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_csvformatprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='format_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_uploads', to='records.csvformatprofile'),
        ),
        migrations.AlterField(
            model_name='csvformatprofile',
            name='field_mappings',
            field=models.JSONField(help_text='Dictionary mapping column index (as string) to model field name'),
        ),
    ]
