# Generated by Django 6.0.2 on 2026-02-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_csvupload_format_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='csvformatprofile',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Default source for uploads using this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_profiles', to='records.source'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_uploads', to='records.source'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='records.source'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='records.source'),
        ),
    ]
