# Generated by Django 6.0.2 on 2026-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_merge_20260224_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='imported_record_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
