# Generated by Django 5.2.12 on 2026-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_seed_restore_backup_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='commission_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
