# Generated by Django 5.2.14 on 2026-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_purchaserecord_order_id_salesrecord_commission_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
