# Generated by Django 5.2.14 on 2026-05-09 17:12

from django.db import migrations


def add_cardmarket_profile(apps, schema_editor):
    CSVFormatProfile = apps.get_model('records', 'CSVFormatProfile')

    CSVFormatProfile.objects.get_or_create(
        name="Cardmarket default",
        defaults={
            "record_type": "sales",
            "delimiter": ";",
            "date_format": "%Y-%m-%d %H:%M:%S",
            "field_mappings": {
                "0": "order_id",
                "1": "item_name",
                "4": "post_code",
                "8": "date",
                "9": "quantity",
                "10": "unit_price",
                "11": "shipping_cost",
                "12": "total_price",
                "13": "commission_cost",
                "14": "currency",
                "15": "notes"
            },
            "has_headers": True,
            "is_active": True,
        }
    )


def remove_cardmarket_profile(apps, schema_editor):
    CSVFormatProfile = apps.get_model('records', 'CSVFormatProfile')
    CSVFormatProfile.objects.filter(name="Cardmarket").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_purchaserecord_notes_alter_salesrecord_notes'),
    ]

    operations = [
        migrations.RunPython(add_cardmarket_profile, remove_cardmarket_profile),
    ]
