# Generated by Django 6.0.2 on 2026-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFormatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], max_length=10)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('date_format', models.CharField(help_text="Python strftime format string, e.g. '%Y-%m-%d' or '%d/%m/%Y'", max_length=50)),
                ('field_mappings', models.JSONField(help_text='Dictionary mapping CSV header names to model field names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CSV Format Profile',
                'verbose_name_plural': 'CSV Format Profiles',
                'ordering': ['name'],
            },
        ),
    ]
