# Generated by Django 5.2.11 on 2026-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_csvupload_format_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
