# Generated by Django 5.2.11 on 2026-02-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_purchaserecord_notes_salesrecord_notes'),
        ('records', '0004_source_csvformatprofile_source_csvupload_source_and_more'),
    ]

    operations = [
    ]
