# Generated by Django 5.2.11 on 2026-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_csvupload_file_hash_csvupload_imported_record_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvformatprofile',
            name='has_headers',
            field=models.BooleanField(default=True, help_text='Whether the CSV file includes a header row as the first row.'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
