# Generated by Django 6.0.2 on 2026-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_csvformatprofile_has_headers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvupload',
            name='file',
        ),
        migrations.AddField(
            model_name='csvupload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
