# Generated by Django 5.2.11 on 2026-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_csvupload_file_csvupload_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('combined', 'Business / Combined')], max_length=20)),
                ('time_window', models.CharField(choices=[('last_7_days', 'Last 7 Days'), ('last_30_days', 'Last 30 Days'), ('this_month', 'This Month'), ('this_year', 'This Year'), ('all_time', 'All Time')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Preset',
                'verbose_name_plural': 'Report Presets',
                'ordering': ['-created_at'],
            },
        ),
    ]
